language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: 9960c435-0d8d-40e9-b6d1-bf910c09106c
  app: mylla-staging
  on:
    repo: qts/lateterm
script: bin/pushToBranch
env:
  global:
    secure: ifoTlGATG98il4vRnyupI9qtK8Yr8aqK2d3d7zBmxhCj7yU5OwEV53AJfyKZrhBM/nj4Oo9TbuGPmln7OyhuD3JnL9/UuA3RMK2itav2x1nR05eVVGvKAz10kvK65nXPQlO+GMHwkT9QtnAbO0ZxKBIQEkEi6MzKrdkd+4YCtzY=
